version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node

    steps:
      - checkout
      
      - run:
          name: Install bundler
          command: bundle
          
      - run:
          name: Greeting
          command: echo Hello, world.
          
      - run:
          name: Run tests
          command: bundle exec rspec spec/*
          
      - run:
          name: Print the Current Time
          command: date
