version: 2
jobs:
  build:
    docker:
      - image: ubuntu:ruby

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.
      -run:
          name: bundle
          command: bundle exec rspec spec/*
          
      - run:
          name: Print the Current Time
          command: date
